# Study 01 — Data Quality Assessment

## Has Morocco's Minimum Wage Protected Workers Against Inflation Since 2000?

### Morocco Economic Intelligence Lab (MEIL)

---

### Objective

This notebook performs a comprehensive quality assessment of the dataset used in Study 01.

The objective is to ensure that all variables are complete, consistent and ready for economic analysis before feature engineering.

---

### Tasks

- Load the dataset
- Verify data structure
- Check variable types
- Detect missing values
- Detect duplicate observations
- Validate the time series
- Produce descriptive statistics
- Export a clean dataset

In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

plt.style.use("default")

## Project Configuration

In [2]:
# -----------------------------------------------------------------------------
# Project Paths
# -----------------------------------------------------------------------------

PROJECT_ROOT = Path.cwd().parent

RAW_DATA = PROJECT_ROOT / "data" / "raw"
PROCESSED_DATA = PROJECT_ROOT / "data" / "processed"
OUTPUTS = PROJECT_ROOT / "outputs"

RAW_FILE = RAW_DATA / "smig_cpi_2000_2024.xlsx"

print(PROJECT_ROOT)
print(RAW_FILE)

c:\Users\oatta\Desktop\Economic Research Projects\Morocco-Economic-Intelligence-Lab\living-standards\study-01-smig-vs-inflation
c:\Users\oatta\Desktop\Economic Research Projects\Morocco-Economic-Intelligence-Lab\living-standards\study-01-smig-vs-inflation\data\raw\smig_cpi_2000_2024.xlsx

## Load Dataset

In [3]:
df = pd.read_excel(RAW_FILE)

df.head()

   year        cpi  smig_monthly
0  2000  83.649753          1826
1  2001  84.168216          1826
2  2002  86.521239          1826
3  2003  87.531577          1826
4  2004  88.838812          1845

## Dataset Overview

In [4]:
print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

df.info()

Rows    : 25
Columns : 3
<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          25 non-null     int64
 1   cpi           25 non-null     float64
 2   smig_monthly  25 non-null     int64
dtypes: float64(1), int64(2)
memory usage: 732.0 bytes

In [5]:
df.columns

Index(['year', 'cpi', 'smig_monthly'], dtype='str')

## First Observations

In [6]:
df.head(10)

   year        cpi  smig_monthly
0  2000  83.649753          1826
1  2001  84.168216          1826
2  2002  86.521239          1826
3  2003  87.531577          1826
4  2004  88.838812          1845
5  2005  89.711779          1845
6  2006  92.658597          1845
7  2007  94.550765          1845
8  2008  98.063177          1936
9  2009  99.016217          2032

## Data Types

In [7]:
df.dtypes

year              int64
cpi             float64
smig_monthly      int64
dtype: object

## Missing Values

In [8]:
missing = df.isna().sum()

missing

year            0
cpi             0
smig_monthly    0
dtype: int64

In [9]:
missing_percentage = df.isna().mean() * 100

missing_percentage

year            0.0
cpi             0.0
smig_monthly    0.0
dtype: float64

## Duplicate Rows

In [10]:
duplicates = df.duplicated().sum()

print(f"Duplicate rows: {duplicates}")

Duplicate rows: 0

## Year Validation

In [12]:
years = df["year"]

print(years.min())
print(years.max())

print(years.is_monotonic_increasing)

2000
2024
True

In [13]:
expected_years = list(range(2000, 2025))

missing_years = sorted(
    set(expected_years) - set(df["year"])
)

missing_years

[]

## Descriptive Statistics

In [14]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
year,25.0,2012.000000,7.359801,2000.000000,2006.000000,2012.00000,2018.000000,2024.000000
cpi,25.0,102.618549,12.751519,83.649753,92.658597,102.20572,110.731614,129.603106
smig_monthly,25.0,2315.000000,447.351372,1826.000000,1845.000000,2337.00000,2570.000000,3111.000000

## Export Clean Dataset

In [15]:
output_file = PROCESSED_DATA / "smig_cpi_2000_2024_clean.csv"

df.to_csv(output_file, index=False)

print("Dataset exported successfully.")

Dataset exported successfully.

## Data Quality Report

In [16]:
print("=" * 60)
print("DATA QUALITY REPORT")
print("=" * 60)

print()

print(f"Observations      : {len(df)}")
print(f"Variables         : {len(df.columns)}")
print(f"Missing values    : {df.isna().sum().sum()}")
print(f"Duplicate rows    : {df.duplicated().sum()}")
print(f"Start year        : {df['year'].min()}")
print(f"End year          : {df['year'].max()}")

print()

print("Dataset Status")

if (
    df.isna().sum().sum() == 0
    and df.duplicated().sum() == 0
):
    print("PASS - Dataset ready for feature engineering.")
else:
    print("WARNING - Dataset requires additional cleaning.")

============================================================
DATA QUALITY REPORT
============================================================

Observations      : 25
Variables         : 3
Missing values    : 0
Duplicate rows    : 0
Start year        : 2000
End year          : 2024

Dataset Status
PASS - Dataset ready for feature engineering.