# Study 01 — Project Packaging

## Has Morocco's Minimum Wage Protected Workers Against Inflation Since 2000?

### Morocco Economic Intelligence Lab (MEIL)

---

## Objective

This notebook packages the study outputs and prepares the project for GitHub publication.

It validates the repository structure, checks the generated artefacts, and creates a final study manifest.

In [4]:
import pandas as pd
from pathlib import Path
from datetime import datetime
import subprocess
from IPython.display import display

In [5]:
NOTEBOOKS_DIR = Path.cwd()
STUDY_ROOT = NOTEBOOKS_DIR.parent
REPO_ROOT = STUDY_ROOT.parents[1]

DATA_DIR = STUDY_ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"

OUTPUTS_DIR = STUDY_ROOT / "outputs"
FIGURES_DIR = OUTPUTS_DIR / "figures"
TABLES_DIR = OUTPUTS_DIR / "tables"

EXEC_SUMMARY_DIR = STUDY_ROOT / "executive-summary"

FEATURE_FILE = PROCESSED_DIR / "smig_cpi_features.csv"
RESULTS_FILE = PROCESSED_DIR / "study_results.csv"
CLEAN_FILE = PROCESSED_DIR / "smig_cpi_2000_2024_clean.csv"
REPORT_FILE = EXEC_SUMMARY_DIR / "study_01_executive_summary.md"
PACKAGE_MANIFEST = STUDY_ROOT / "study_01_package_manifest.md"

print("Notebook directory :", NOTEBOOKS_DIR)
print("Study root         :", STUDY_ROOT)
print("Repo root          :", REPO_ROOT)

Notebook directory : c:\Users\oatta\Desktop\Economic Research Projects\Morocco-Economic-Intelligence-Lab\living-standards\study-01-smig-vs-inflation\notebooks
Study root         : c:\Users\oatta\Desktop\Economic Research Projects\Morocco-Economic-Intelligence-Lab\living-standards\study-01-smig-vs-inflation
Repo root          : c:\Users\oatta\Desktop\Economic Research Projects\Morocco-Economic-Intelligence-Lab

## Expected Repository Structure

In [6]:
expected_repo_paths = [
    REPO_ROOT / "README.md",
    REPO_ROOT / "LICENSE",
    REPO_ROOT / "requirements.txt",
    REPO_ROOT / ".gitignore",
    REPO_ROOT / "living-standards",
]

expected_study_paths = [
    STUDY_ROOT / "README.md",
    STUDY_ROOT / "methodology",
    STUDY_ROOT / "references",
    STUDY_ROOT / "data" / "raw",
    STUDY_ROOT / "data" / "processed",
    STUDY_ROOT / "notebooks",
    STUDY_ROOT / "outputs" / "figures",
    STUDY_ROOT / "outputs" / "tables",
    STUDY_ROOT / "executive-summary",
]

missing_repo_paths = [str(path) for path in expected_repo_paths if not path.exists()]
missing_study_paths = [str(path) for path in expected_study_paths if not path.exists()]

print("Repo-level checks")
if missing_repo_paths:
    for path in missing_repo_paths:
        print(" -", path)
else:
    print("All repo-level paths are present.")

print()
print("Study-level checks")
if missing_study_paths:
    for path in missing_study_paths:
        print(" -", path)
else:
    print("All study-level paths are present.")

Repo-level checks
All repo-level paths are present.

Study-level checks
All study-level paths are present.

## Study Artefacts Overview

In [7]:
artefacts = pd.DataFrame([
    {"File": "smig_cpi_2000_2024_clean.csv", "Exists": CLEAN_FILE.exists(), "Path": str(CLEAN_FILE)},
    {"File": "smig_cpi_features.csv", "Exists": FEATURE_FILE.exists(), "Path": str(FEATURE_FILE)},
    {"File": "study_results.csv", "Exists": RESULTS_FILE.exists(), "Path": str(RESULTS_FILE)},
    {"File": "study_01_executive_summary.md", "Exists": REPORT_FILE.exists(), "Path": str(REPORT_FILE)},
])

display(artefacts)

,File,Exists,Path
0,smig_cpi_2000_2024_clean.csv,True,c:\Users\oatta\Desktop\Economic Research Proje...
1,smig_cpi_features.csv,True,c:\Users\oatta\Desktop\Economic Research Proje...
2,study_results.csv,True,c:\Users\oatta\Desktop\Economic Research Proje...
3,study_01_executive_summary.md,True,c:\Users\oatta\Desktop\Economic Research Proje...

## Figures Inventory

In [8]:
if FIGURES_DIR.exists():
    figure_files = sorted(FIGURES_DIR.glob("*.png"))
    figures_df = pd.DataFrame([
        {
            "Figure": file.name,
            "Exists": file.exists(),
            "Size_KB": round(file.stat().st_size / 1024, 2)
        }
        for file in figure_files
    ])
else:
    figures_df = pd.DataFrame(columns=["Figure", "Exists", "Size_KB"])

display(figures_df)

                                    Figure  Exists  Size_KB
0        figure_01_executive_dashboard.png    True   204.47
1                figure_01_smig_vs_cpi.png    True   123.02
2                    figure_02_base100.png    True   170.47
3         figure_02_base100_comparison.png    True   170.47
4                  figure_03_inflation.png    True    67.34
5       figure_03_purchasing_power_gap.png    True    82.48
6                       figure_04_pppr.png    True   166.02
7                figure_04_wage_growth.png    True    73.68
8   figure_05_inflation_vs_wage_growth.png    True   278.46
9                  figure_05_real_wage.png    True   160.43
10         figure_06_cumulative_growth.png    True   177.02
11                       figure_06_gap.png    True    81.84
12                      figure_07_pppr.png    True   164.33
13      figure_07_revaluation_timeline.png    True    75.23
14          figure_08_economic_heatmap.png    True   170.93

## Tables Inventory

In [11]:
if TABLES_DIR.exists():
    table_files = sorted(TABLES_DIR.glob("*"))
    if table_files:
        tables_df = pd.DataFrame([
            {
                "File": file.name,
                "Exists": file.exists(),
                "Size_KB": round(file.stat().st_size / 1024, 2) if file.is_file() else None
            }
            for file in table_files
        ])
        display(tables_df)
    else:
        print("No table files found in outputs/tables.")
else:
    print("The tables directory does not exist.")

No table files found in outputs/tables.

## Git Status

In [12]:
try:
    result = subprocess.run(
        ["git", "status", "--short"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False
    )

    if result.stdout.strip():
        print(result.stdout)
    else:
        print("Working tree clean or no tracked changes yet.")
except FileNotFoundError:
    print("Git is not available in this environment.")

?? .gitignore
?? LICENSE
?? README.md
?? living-standards/
?? requirements.txt

## Study Statistics

In [13]:
results = pd.read_csv(RESULTS_FILE).iloc[0].to_dict()

summary_stats = pd.DataFrame([
    {"Metric": "Study period", "Value": results.get("study_period")},
    {"Metric": "Observations", "Value": results.get("observations")},
    {"Metric": "Average inflation (%)", "Value": results.get("average_inflation")},
    {"Metric": "Average nominal wage growth (%)", "Value": results.get("average_nominal_growth")},
    {"Metric": "Average real wage growth (%)", "Value": results.get("average_real_growth")},
    {"Metric": "Average PPPR", "Value": results.get("average_pppr")},
    {"Metric": "Years above inflation", "Value": results.get("years_above_inflation")},
    {"Metric": "Years below inflation", "Value": results.get("years_below_inflation")},
    {"Metric": "Best year", "Value": results.get("best_year")},
    {"Metric": "Worst year", "Value": results.get("worst_year")},
    {"Metric": "Cumulative real gain (%)", "Value": results.get("cumulative_real_gain")},
])

display(summary_stats)

                             Metric      Value
0                      Study period  2000-2024
1                      Observations         25
2             Average inflation (%)       1.85
3   Average nominal wage growth (%)       2.28
4      Average real wage growth (%)       0.43
5                      Average PPPR      1.026
6             Years above inflation          8
7             Years below inflation         16
8                         Best year       2011
9                        Worst year       2006
10         Cumulative real gain (%)      15.44

## Build Study Manifest

In [14]:
def bullet_list(items):
    return "\n".join([f"- {item}" for item in items])

manifest_lines = []

manifest_lines.append("# Study 01 — Package Manifest")
manifest_lines.append("")
manifest_lines.append("## Has Morocco's Minimum Wage Protected Workers Against Inflation Since 2000?")
manifest_lines.append("")
manifest_lines.append("### Morocco Economic Intelligence Lab (MEIL)")
manifest_lines.append("")
manifest_lines.append(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
manifest_lines.append("")
manifest_lines.append("## Core Artefacts")
manifest_lines.append("")
manifest_lines.append(bullet_list([
    f"smig_cpi_2000_2024_clean.csv — {'present' if CLEAN_FILE.exists() else 'missing'}",
    f"smig_cpi_features.csv — {'present' if FEATURE_FILE.exists() else 'missing'}",
    f"study_results.csv — {'present' if RESULTS_FILE.exists() else 'missing'}",
    f"study_01_executive_summary.md — {'present' if REPORT_FILE.exists() else 'missing'}",
]))
manifest_lines.append("")
manifest_lines.append("## Figures")
manifest_lines.append("")

if not figures_df.empty:
    for _, row in figures_df.iterrows():
        manifest_lines.append(f"- {row['Figure']} ({row['Size_KB']} KB)")
else:
    manifest_lines.append("- No figures found.")

manifest_lines.append("")
manifest_lines.append("## Key Study Statistics")
manifest_lines.append("")
for _, row in summary_stats.iterrows():
    manifest_lines.append(f"- {row['Metric']}: {row['Value']}")

manifest_lines.append("")
manifest_lines.append("## Repository Notes")
manifest_lines.append("")
manifest_lines.append("- The study follows a modular notebook workflow.")
manifest_lines.append("- All outputs are stored inside the study folder.")
manifest_lines.append("- The report is ready for GitHub publication.")
manifest_lines.append("")
manifest_lines.append("## Publication Checklist")
manifest_lines.append("")
manifest_lines.append("- [x] Data quality validated")
manifest_lines.append("- [x] Feature engineering completed")
manifest_lines.append("- [x] Exploratory analysis completed")
manifest_lines.append("- [x] Economic analysis completed")
manifest_lines.append("- [x] Statistical analysis completed")
manifest_lines.append("- [x] Publication-quality figures generated")
manifest_lines.append("- [x] Executive summary exported")
manifest_lines.append("- [x] Package manifest created")

package_md = "\n".join(manifest_lines)

print(package_md[:4000])

# Study 01 — Package Manifest

## Has Morocco's Minimum Wage Protected Workers Against Inflation Since 2000?

### Morocco Economic Intelligence Lab (MEIL)

Generated on: 2026-07-25 20:01:19

## Core Artefacts

- smig_cpi_2000_2024_clean.csv — present
- smig_cpi_features.csv — present
- study_results.csv — present
- study_01_executive_summary.md — present

## Figures

- figure_01_executive_dashboard.png (204.47 KB)
- figure_01_smig_vs_cpi.png (123.02 KB)
- figure_02_base100.png (170.47 KB)
- figure_02_base100_comparison.png (170.47 KB)
- figure_03_inflation.png (67.34 KB)
- figure_03_purchasing_power_gap.png (82.48 KB)
- figure_04_pppr.png (166.02 KB)
- figure_04_wage_growth.png (73.68 KB)
- figure_05_inflation_vs_wage_growth.png (278.46 KB)
- figure_05_real_wage.png (160.43 KB)
- figure_06_cumulative_growth.png (177.02 KB)
- figure_06_gap.png (81.84 KB)
- figure_07_pppr.png (164.33 KB)
- figure_07_revaluation_timeline.png (75.23 KB)
- figure_08_economic_heatmap.png (170.93 KB)

## Key Study Statistics

- Study period: 2000-2024
- Observations: 25
- Average inflation (%): 1.85
- Average nominal wage growth (%): 2.28
- Average real wage growth (%): 0.43
- Average PPPR: 1.026
- Years above inflation: 8
- Years below inflation: 16
- Best year: 2011
- Worst year: 2006
- Cumulative real gain (%): 15.44

## Repository Notes

- The study follows a modular notebook workflow.
- All outputs are stored inside the study folder.
- The report is ready for GitHub publication.

## Publication Checklist

- [x] Data quality validated
- [x] Feature engineering completed
- [x] Exploratory analysis completed
- [x] Economic analysis completed
- [x] Statistical analysis completed
- [x] Publication-quality figures generated
- [x] Executive summary exported
- [x] Package manifest created

In [15]:
with open(PACKAGE_MANIFEST, "w", encoding="utf-8") as f:
    f.write(package_md)

print(f"Package manifest exported successfully to: {PACKAGE_MANIFEST}")

Package manifest exported successfully to: c:\Users\oatta\Desktop\Economic Research Projects\Morocco-Economic-Intelligence-Lab\living-standards\study-01-smig-vs-inflation\study_01_package_manifest.md

## Final Publication Readiness Check

In [16]:
required_files = [
    CLEAN_FILE,
    FEATURE_FILE,
    RESULTS_FILE,
    REPORT_FILE,
    PACKAGE_MANIFEST,
]

required_figures = [
    FIGURES_DIR / "figure_01_executive_dashboard.png",
    FIGURES_DIR / "figure_02_base100_comparison.png",
    FIGURES_DIR / "figure_03_purchasing_power_gap.png",
    FIGURES_DIR / "figure_04_pppr.png",
    FIGURES_DIR / "figure_05_inflation_vs_wage_growth.png",
    FIGURES_DIR / "figure_06_cumulative_growth.png",
    FIGURES_DIR / "figure_07_revaluation_timeline.png",
    FIGURES_DIR / "figure_08_economic_heatmap.png",
]

missing_required = [str(path) for path in required_files if not path.exists()]
missing_figures = [str(path) for path in required_figures if not path.exists()]

print("=" * 70)
print("PUBLICATION READINESS CHECK")
print("=" * 70)
print()

if missing_required:
    print("Missing required files:")
    for item in missing_required:
        print(" -", item)
else:
    print("All required study files are present.")

print()

if missing_figures:
    print("Missing required figures:")
    for item in missing_figures:
        print(" -", item)
else:
    print("All required publication figures are present.")

print()

if not missing_required and not missing_figures:
    print("STATUS: READY FOR GITHUB PUBLICATION")
else:
    print("STATUS: NOT READY — fix missing artefacts first.")

======================================================================
PUBLICATION READINESS CHECK
======================================================================

All required study files are present.

All required publication figures are present.

STATUS: READY FOR GITHUB PUBLICATION

## Package Summary

In [17]:
print("Project packaging completed successfully.")
print()
print(f"Manifest file : {PACKAGE_MANIFEST}")
print(f"Figures folder : {FIGURES_DIR}")
print(f"Report folder  : {EXEC_SUMMARY_DIR}")
print()
print("Study 01 is ready for final GitHub cleanup and publication.")

Project packaging completed successfully.

Manifest file : c:\Users\oatta\Desktop\Economic Research Projects\Morocco-Economic-Intelligence-Lab\living-standards\study-01-smig-vs-inflation\study_01_package_manifest.md
Figures folder : c:\Users\oatta\Desktop\Economic Research Projects\Morocco-Economic-Intelligence-Lab\living-standards\study-01-smig-vs-inflation\outputs\figures
Report folder  : c:\Users\oatta\Desktop\Economic Research Projects\Morocco-Economic-Intelligence-Lab\living-standards\study-01-smig-vs-inflation\executive-summary

Study 01 is ready for final GitHub cleanup and publication.