In [2]:
# ============================================================
# 02 - FEATURE ENGINEERING
# HOUSEHOLD PURCHASING POWER IN MOROCCO
# PERIOD: 2007-2024
# ============================================================

import pandas as pd
import numpy as np

pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

file_path = (
    "../data/processed/"
    "study_02_household_purchasing_power_2007_2024.xlsx"
)

df = pd.read_excel(
    file_path,
    sheet_name="master_data"
)

print("File loaded successfully.")
print("Shape:", df.shape)

display(df.head())

File loaded successfully.
Shape: (19, 4)

,year,cpi_base_2017_harmonized,disposable_income_s14_harmonized,consumption_s14_harmonized
0,2007,86.67,"481,012.00","414,786.00"
1,2008,89.88,"529,868.00","462,466.00"
2,2009,90.81,"567,820.00","485,171.00"
3,2010,91.65,"589,668.00","509,474.00"
4,2011,92.50,"621,887.00","539,099.00"

In [4]:
# ============================================================
# VERIFY AND RESTRICT STUDY PERIOD
# ============================================================

# Convert year to numeric
df["year"] = pd.to_numeric(df["year"], errors="coerce")

# Keep only the official study period
df = df[
    (df["year"] >= 2007) &
    (df["year"] <= 2024)
].copy()

# Convert year to integer
df["year"] = df["year"].astype(int)

# Sort chronologically
df = df.sort_values("year").reset_index(drop=True)

# Validation
expected_columns = [
    "year",
    "cpi_base_2017_harmonized",
    "disposable_income_s14_harmonized",
    "consumption_s14_harmonized"
]

assert df.columns.tolist() == expected_columns, (
    "Unexpected column structure"
)

assert df["year"].min() == 2007
assert df["year"].max() == 2024
assert len(df) == 18

assert df.isna().sum().sum() == 0, (
    "Missing values detected"
)

print("Dataset structure: VALID")
print("Shape:", df.shape)
print("Period:", df["year"].min(), "-", df["year"].max())
print("Missing values:", df.isna().sum().sum())

display(df)

Dataset structure: VALID
Shape: (18, 4)
Period: 2007 - 2024
Missing values: 0

,year,cpi_base_2017_harmonized,disposable_income_s14_harmonized,consumption_s14_harmonized
0,2007,86.67,"481,012.00","414,786.00"
1,2008,89.88,"529,868.00","462,466.00"
2,2009,90.81,"567,820.00","485,171.00"
3,2010,91.65,"589,668.00","509,474.00"
4,2011,92.50,"621,887.00","539,099.00"
5,2012,93.68,"646,024.00","565,253.00"
6,2013,95.46,"686,838.00","593,930.00"
7,2014,95.88,"696,519.00","612,719.00"
8,2015,97.40,"731,268.00","628,994.00"
9,2016,99.01,"731,112.00","642,181.00"
10,2017,99.69,"773,432.00","673,764.00"
11,2018,101.55,"795,093.00","702,020.00"
12,2019,101.80,"823,573.00","723,177.00"
13,2020,102.50,"793,178.00","672,606.00"
14,2021,103.90,"869,067.00","750,896.00"
15,2022,110.80,"913,301.00","816,977.00"
16,2023,117.60,"1,000,495.00","895,003.00"
17,2024,118.70,"1,077,016.00","944,065.00"

In [5]:
# ============================================================
# CREATE ANALYTICAL VARIABLES
# ============================================================

# Real disposable income
df["real_disposable_income"] = (
    df["disposable_income_s14_harmonized"]
    / df["cpi_base_2017_harmonized"]
    * 100
)

# Real consumption
df["real_consumption"] = (
    df["consumption_s14_harmonized"]
    / df["cpi_base_2017_harmonized"]
    * 100
)

# Annual inflation rate
df["inflation"] = (
    df["cpi_base_2017_harmonized"]
    .pct_change()
    * 100
)

# Growth rate of real disposable income
df["real_disposable_income_growth"] = (
    df["real_disposable_income"]
    .pct_change()
    * 100
)

# Growth rate of real consumption
df["real_consumption_growth"] = (
    df["real_consumption"]
    .pct_change()
    * 100
)

# Saving rate
df["saving_rate"] = (
    (
        df["disposable_income_s14_harmonized"]
        - df["consumption_s14_harmonized"]
    )
    / df["disposable_income_s14_harmonized"]
    * 100
)

print("Analytical variables created successfully.")
display(df.head())

Analytical variables created successfully.

,year,cpi_base_2017_harmonized,disposable_income_s14_harmonized,consumption_s14_harmonized,real_disposable_income,real_consumption,inflation,real_disposable_income_growth,real_consumption_growth,saving_rate
0,2007,86.67,"481,012.00","414,786.00","555,022.60","478,606.78",NaN,NaN,NaN,13.77
1,2008,89.88,"529,868.00","462,466.00","589,540.07","514,547.47",3.71,6.22,7.51,12.72
2,2009,90.81,"567,820.00","485,171.00","625,295.26","534,280.46",1.03,6.06,3.84,14.56
3,2010,91.65,"589,668.00","509,474.00","643,364.49","555,867.84",0.93,2.89,4.04,13.60
4,2011,92.50,"621,887.00","539,099.00","672,315.36","582,814.14",0.92,4.50,4.85,13.31

In [6]:
# ============================================================
# ROUND ANALYTICAL VARIABLES
# ============================================================

df["real_disposable_income"] = (
    df["real_disposable_income"].round(2)
)

df["real_consumption"] = (
    df["real_consumption"].round(2)
)

df["inflation"] = (
    df["inflation"].round(2)
)

df["real_disposable_income_growth"] = (
    df["real_disposable_income_growth"].round(2)
)

df["real_consumption_growth"] = (
    df["real_consumption_growth"].round(2)
)

df["saving_rate"] = (
    df["saving_rate"].round(2)
)

display(df)

,year,cpi_base_2017_harmonized,disposable_income_s14_harmonized,consumption_s14_harmonized,real_disposable_income,real_consumption,inflation,real_disposable_income_growth,real_consumption_growth,saving_rate
0,2007,86.67,"481,012.00","414,786.00","555,022.60","478,606.78",NaN,NaN,NaN,13.77
1,2008,89.88,"529,868.00","462,466.00","589,540.07","514,547.47",3.71,6.22,7.51,12.72
2,2009,90.81,"567,820.00","485,171.00","625,295.26","534,280.46",1.03,6.06,3.84,14.56
3,2010,91.65,"589,668.00","509,474.00","643,364.49","555,867.84",0.93,2.89,4.04,13.60
4,2011,92.50,"621,887.00","539,099.00","672,315.36","582,814.14",0.92,4.50,4.85,13.31
5,2012,93.68,"646,024.00","565,253.00","689,584.35","603,367.10",1.28,2.57,3.53,12.50
6,2013,95.46,"686,838.00","593,930.00","719,514.01","622,185.95",1.90,4.34,3.12,13.53
7,2014,95.88,"696,519.00","612,719.00","726,438.08","639,038.44",0.44,0.96,2.71,12.03
8,2015,97.40,"731,268.00","628,994.00","750,763.06","645,762.52",1.59,3.35,1.05,13.99
9,2016,99.01,"731,112.00","642,181.00","738,423.87","648,603.47",1.65,-1.64,0.44,12.16
10,2017,99.69,"773,432.00","673,764.00","775,866.67","675,884.93",0.68,5.07,4.21,12.89
11,2018,101.55,"795,093.00","702,020.00","782,988.01","691,332.01",1.87,0.92,2.29,11.71
12,2019,101.80,"823,573.00","723,177.00","809,010.81","710,389.98",0.25,3.32,2.76,12.19
13,2020,102.50,"793,178.00","672,606.00","773,832.20","656,200.98",0.69,-4.35,-7.63,15.20
14,2021,103.90,"869,067.00","750,896.00","836,445.62","722,710.30",1.37,8.09,10.14,13.60
15,2022,110.80,"913,301.00","816,977.00","824,278.88","737,343.86",6.64,-1.45,2.02,10.55
16,2023,117.60,"1,000,495.00","895,003.00","850,761.05","761,056.97",6.14,3.21,3.22,10.54
17,2024,118.70,"1,077,016.00","944,065.00","907,342.88","795,336.98",0.94,6.65,4.50,12.34

In [7]:
# ============================================================
# FINAL VALIDATION
# ============================================================

print("Dataset shape:", df.shape)

print("\nColumns:")
for column in df.columns:
    print("-", column)

print("\nMissing values:")
print(df.isna().sum())

display(df.describe().T)

Dataset shape: (18, 10)

Columns:
- year
- cpi_base_2017_harmonized
- disposable_income_s14_harmonized
- consumption_s14_harmonized
- real_disposable_income
- real_consumption
- inflation
- real_disposable_income_growth
- real_consumption_growth
- saving_rate

Missing values:
year                                0
cpi_base_2017_harmonized            0
disposable_income_s14_harmonized    0
consumption_s14_harmonized          0
real_disposable_income              0
real_consumption                    0
inflation                           1
real_disposable_income_growth       1
real_consumption_growth             1
saving_rate                         0
dtype: int64

,count,mean,std,min,25%,50%,75%,max
year,18.00,"2,015.50",5.34,"2,007.00","2,011.25","2,015.50","2,019.75","2,024.00"
cpi_base_2017_harmonized,18.00,99.42,8.99,86.67,92.80,98.21,102.33,118.70
disposable_income_s14_harmonized,18.00,"740,398.39","159,635.89","481,012.00","627,921.25","731,190.00","816,453.00","1,077,016.00"
consumption_s14_harmonized,18.00,"646,254.50","144,583.41","414,786.00","545,637.50","635,587.50","717,887.75","944,065.00"
real_disposable_income,18.00,"737,265.96","94,799.66","555,022.60","676,632.61","744,593.47","802,505.11","907,342.88"
real_consumption,18.00,"643,073.90","87,161.00","478,606.78","587,952.38","647,182.99","705,625.49","795,336.98"
inflation,17.00,1.88,1.87,0.25,0.92,1.28,1.87,6.64
real_disposable_income_growth,17.00,2.98,3.27,-4.35,0.96,3.32,5.07,8.09
real_consumption_growth,17.00,3.09,3.58,-7.63,2.29,3.22,4.21,10.14
saving_rate,18.00,12.84,1.24,10.54,12.17,12.80,13.60,15.20

In [8]:
# ============================================================
# EXPORT ANALYTICAL DATASET
# ============================================================

output_path = (
    "../data/processed/"
    "study_02_household_purchasing_power_analytical_2007_2024.xlsx"
)

df.to_excel(
    output_path,
    index=False
)

print("Analytical dataset exported successfully.")
print("File:", output_path)

Analytical dataset exported successfully.
File: ../data/processed/study_02_household_purchasing_power_analytical_2007_2024.xlsx